After verification, keep the Bitcoin Core tarball and guix.sigs/  in ~/Downloads/  (#151)
* Keep bitcoin tarball and guix.sigs in ~/Downloads/

* Fix variable name

* Fix bug with variable name

* Fix bug when guix.sigs already exists

* Roll back code changes due to a runtime error

* Improve terminal output

* Remove the temp directory if it's unnecessary

diff --git a/nodebuilder b/nodebuilder
--- a/nodebuilder
+++ b/nodebuilder
@@ -17,10 +17,12 @@ guix_sigs_repo="https://github.com/bitcoin-core/guix.sigs.git"
 
 tmp_dir="$(mktemp -d)"
 trap 'rm -rf -- "$tmp_dir"' EXIT
-bitcoin_tarball_file="${tmp_dir}/${bitcoin_tarball_filename}"
+bitcoin_tarball_temporary_file="${tmp_dir}/${bitcoin_tarball_filename}"
+bitcoin_tarball_destination_file="${HOME}/Downloads/${bitcoin_tarball_filename}"
 bitcoin_hash_file="${tmp_dir}/${bitcoin_hash_filename}"
 gpg_signatures_file="${tmp_dir}/${gpg_signatures_filename}"
-guix_sigs_clone_dir="${tmp_dir}/guix.sigs"
+guix_sigs_temporary_dir="${tmp_dir}/guix.sigs"
+guix_sigs_destination_dir="${HOME}/Downloads/guix.sigs"
 
 bitcoin_core_extract_dir="${HOME}/bitcoin"
 bitcoin_core_binary_dir="${bitcoin_core_extract_dir}/bin"
@@ -62,57 +64,62 @@ if [ -f /var/run/reboot-required ]; then
 fi
 
 # Install dependencies
-echo "Checking dependencies... "
+echo "Checking for dependencies... "
 sudo apt-get -qq update && sudo apt-get -qq install --assume-yes --no-install-recommends curl git gnupg jq libxcb-xinerama0
 
-echo -n "Downloading Bitcoin Core files... "
-[ -d "${tmp_dir}" ] || mkdir "${tmp_dir}"/
-[ -f "${bitcoin_tarball_file}" ] || curl --silent --show-error --location --fail --output "${bitcoin_tarball_file}" "${bitcoin_tarball_file_source}"
-[ -f "${bitcoin_hash_file}" ] || curl --silent --show-error --location --fail --output "${bitcoin_hash_file}" "${bitcoin_hash_file_source}"
-[ -f "${gpg_signatures_file}" ] || curl --silent --show-error --location --fail --output "${gpg_signatures_file}" "${gpg_signatures_file_source}"
-echo "ok."
-
-# Check that the release file's checksum is listed in SHA256SUMS
-echo -n "  Validating the checksum... "
-cd "${tmp_dir}"/
-sha256_check=$(grep ${bitcoin_tarball_filename} ${bitcoin_hash_filename} | sha256sum --check 2> /dev/null)
-cd "${HOME}"/
-if [[ "${sha256_check}" == *"OK" ]]; then
+echo -n "Checking for Bitcoin Core... "
+if [ -f "${bitcoin_tarball_destination_file}" ]; then
+  rm -r "${tmp_dir:?}"/
   echo "ok."
 else
-  err "INVALID. The download has failed. This script cannot continue due to security concerns."
-  err "Please review the temporary file ${tmp_dir}/${bitcoin_hash_file}."
-  echo -en "\nPRESS ANY KEY to exit... "
-  read -rsn1 && echo
-  echo "Exiting."
-  exit 1
-fi
+  echo
+  echo -n "  Downloading Bitcoin Core... "
+  curl --silent --show-error --location --fail --output "${bitcoin_tarball_temporary_file}" "${bitcoin_tarball_file_source}"
+  curl --silent --show-error --location --fail --output "${bitcoin_hash_file}" "${bitcoin_hash_file_source}"
+  curl --silent --show-error --location --fail --output "${gpg_signatures_file}" "${gpg_signatures_file_source}"
+  echo "ok"
 
-# Check the PGP signatures of SHA256SUMS
-echo -n "  Validating the signatures... "
-[ -d "${guix_sigs_clone_dir}"/ ] || git clone --quiet "${guix_sigs_repo}" "${guix_sigs_clone_dir}"
-gpg --quiet --import "${guix_sigs_clone_dir}"/builder-keys/*.gpg
-gpg_good_signature_count=$(gpg --verify "${gpg_signatures_file}" 2>&1 | grep -c "^gpg: Good signature from ")
-if [[ "${gpg_good_signature_count}" -ge "${gpg_good_signatures_required}" ]]; then
-  echo "${gpg_good_signature_count} good."
-  rm "${bitcoin_hash_file}"
-  rm "${gpg_signatures_file}"
-  rm -rf "${guix_sigs_clone_dir:?}"/
-  mv "${bitcoin_tarball_file}" "${HOME}"/"${bitcoin_tarball_filename}"
-  bitcoin_tarball_file="${HOME}/${bitcoin_tarball_filename}"
-  rm -r "${tmp_dir:?}"/
-else
-  err "INVALID. The download has failed. This script cannot continue due to security concerns."
-  err "Please review the temporary file ${tmp_dir}/${gpg_signatures_file}."
-  echo -en "\nPRESS ANY KEY to exit... "
-  read -rsn1 && echo
-  echo "Exiting."
-  exit 1
+  # Check that the release file's checksum is listed in SHA256SUMS
+  echo -n "  Validating the checksum... "
+  cd "${tmp_dir}"/
+  sha256_check=$(grep ${bitcoin_tarball_filename} ${bitcoin_hash_filename} | sha256sum --check 2> /dev/null)
+  cd "${HOME}"/
+  if [[ "${sha256_check}" == *"OK" ]]; then
+    echo "ok."
+  else
+    err "INVALID. The download has failed. This script cannot continue due to security concerns."
+    err "Please review the temporary file ${tmp_dir}/${bitcoin_hash_file}."
+    echo -en "\nPRESS ANY KEY to exit... "
+    read -rsn1 && echo
+    echo "Exiting."
+    exit 1
+  fi
+
+  # Check the PGP signatures of SHA256SUMS
+  echo -n "  Validating the signatures... "
+  [ -d "${guix_sigs_destination_dir}"/ ] || git clone --quiet "${guix_sigs_repo}" "${guix_sigs_temporary_dir}"
+  gpg --quiet --import "${guix_sigs_temporary_dir}"/builder-keys/*.gpg
+  gpg_good_signature_count=$(gpg --verify "${gpg_signatures_file}" 2>&1 | grep -c "^gpg: Good signature from ")
+  if [[ "${gpg_good_signature_count}" -ge "${gpg_good_signatures_required}" ]]; then
+    echo "${gpg_good_signature_count} good."
+    mv "${bitcoin_tarball_temporary_file}" "${bitcoin_tarball_destination_file}"
+    [ -d "${guix_sigs_destination_dir}"/ ] || mv "${guix_sigs_temporary_dir}" "${guix_sigs_destination_dir}"
+    rm "${bitcoin_hash_file}"
+    rm "${gpg_signatures_file}"
+    rm -r "${tmp_dir:?}"/
+  else
+    err "INVALID. The download has failed. This script cannot continue due to security concerns."
+    err "Please review the temporary file ${tmp_dir}/${gpg_signatures_file}."
+    echo -en "\nPRESS ANY KEY to exit... "
+    read -rsn1 && echo
+    echo "Exiting."
+    exit 1
+  fi
 fi
 
 echo -n "Extracting Bitcoin Core... "
 [ -d "${bitcoin_core_extract_dir}" ] || mkdir "${bitcoin_core_extract_dir}"/
-tar -xzf "${bitcoin_tarball_file}" -C "${bitcoin_core_extract_dir}"/ --strip-components=1
+tar -xzf "${bitcoin_tarball_destination_file}" -C "${bitcoin_core_extract_dir}"/ --strip-components=1
 echo "ok."
 
 echo -n "Running unit tests... "
